# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.runs/synth_1/.Xil/Vivado-28620-DESKTOP-55513A7/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -include D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new {
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.runs/synth_1/.Xil/Vivado-28620-DESKTOP-55513A7/realtime/dist_mem_gen_0_stub.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/StallCtrl.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/Regfile.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/PC.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/IF_ID.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/ID_EX.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/ID.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/MEM_WB.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/MEM.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/EX_MEM.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/EX.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/DMEM.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/CPU.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/IMEM.v
      D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.runs/synth_1/.Xil/Vivado-28620-DESKTOP-55513A7/realtime/top_synth.xdc
    rt::sdcChecksum
    set rt::top top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.cache/wt}
    rt::set_parameter enableSplitFlowPath "D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.runs/synth_1/.Xil/Vivado-28620-DESKTOP-55513A7/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
