# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.cache/wt [current_project]
set_property parent.project_path D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/testcases/_dropEggs.coe
add_files -quiet d:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/defines.v
set_property file_type "Verilog Header" [get_files D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/defines.v]
read_verilog -library xil_defaultlib {
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/StallCtrl.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/Regfile.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/PC.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/IF_ID.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/ID_EX.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/ID.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/MEM_WB.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/MEM.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/EX_MEM.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/EX.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/DMEM.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/CPU.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/IMEM.v
  D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/constrs_1/new/tb.xdc
set_property used_in_implementation false [get_files D:/Projects/Vivado/MIPS32_Pipeline/MIPS32_Pipeline.srcs/constrs_1/new/tb.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
